repos:
    - repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 0.971
      hooks:
          - id: mypy
