name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os-name: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11"]
    name: Python ${{ matrix.python-version }} (${{ matrix.os-name }})
    runs-on: ${{ matrix.os-name }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install developer dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Run nox
        run: nox -p ${{ matrix.python-version }}
      - name: Upload coverage report
        if: ${{ matrix.os-name == 'ubuntu-latest' && matrix.python-version == '3.10' }}
        uses: codecov/codecov-action@v3
        with:
            files: coverage.xml
            verbose: true
